// This file is generated from the Rust desktop protocol by `cargo run -p koharu-app --bin generate`.
// Do not edit it by hand.

// This file has been generated by Specta. Do not edit this file manually.
export type AotInpaintingConfig = {
	max_side?: number,
};

export type AssetView = {
	clean: string | null,
	rendered: string | null,
	text_mask: string | null,
	coo_mask: string | null,
	bubble_mask: string | null,
	brush_mask: string | null,
};

export type BaberuOcrConfig = Record<string, never>;

export type BevelStyle = "Inner" | "Outer" | "Emboss" | "Pillow" | "Stroke";

export type BlendMode = "Normal" | "Multiply" | "Screen" | "Overlay" | "Darken" | "Lighten" | "ColorDodge" | "ColorBurn" | "HardLight" | "SoftLight" | "Difference" | "Exclusion";

export type BlobId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type BridgeEvent = { type: "app"; payload: UiEvent };

export type BridgeMessage = { type: "ready"; dpr: number; width: number; height: number } | { type: "viewport"; x: number; y: number; width: number; height: number; dpr: number; background: [number, number, number] } | { type: "window"; action: WindowAction } | { type: "command"; id: RequestId; base: Revision; command: UiCommand } | { type: "interaction"; interaction: CanvasInteraction };

export type CaiyunConfig = Record<string, never>;

export type CanvasBrushCursor = {
	x: number,
	y: number,
	diameter: number,
};

export type CanvasDisplay = {
	page: CanvasPageView,
	show_text: boolean,
	text_mask: CanvasMaskOverlay | null,
	brush_mask: CanvasMaskOverlay | null,
};

export type CanvasGuide = { axis: "horizontal"; position: number } | { axis: "vertical"; position: number };

export type CanvasInteraction = { type: "show_page"; page: PageId } | { type: "set_camera"; zoom: number; translation: [number, number] } | { type: "set_zoom"; zoom: number } | { type: "fit_window" } | { type: "set_display"; display: CanvasDisplay } | { type: "set_overlays"; selected: ElementId[]; hovered: ElementId | null; draft: Frame | null; guides: CanvasGuide[]; show_text_bounds: boolean; brush_cursor: CanvasBrushCursor | null } | { type: "hit_test"; id: number; x: number; y: number } | { type: "begin_transform"; elements: ElementId[]; target: HitTarget; x: number; y: number } | { type: "update_transform"; x: number; y: number } | { type: "cancel_transform" } | { type: "begin_mask_stroke"; plane: MaskPlane; diameter: number; erase: boolean; x: number; y: number } | { type: "extend_mask_stroke"; x: number; y: number } | { type: "finish_mask_stroke" } | { type: "cancel_mask_stroke" };

export type CanvasMaskOverlay = {
	tint: [number, number, number, number],
	opacity: number,
};

export type CanvasPageView = "source" | "clean" | "rendered";

export type ClaudeConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type DeepLConfig = {
	base_url?: string | null,
};

export type DeepSeekConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type DetectionModel = {
	model: "koharu-layout-rfdetr-seg-2xl",
} & KoharuLayoutRFDetrSeg2XLConfig;

export type DownloadStatus = { state: "running"; id: number; name: string; completed: number; total: number } | { state: "finished"; id: number } | { state: "failed"; id: number; name: string; error: string };

export type Element = {
	id: ElementId,
	frame: Frame,
	visible: boolean,
	opacity: number,
	kind: ElementKind,
};

export type ElementFrame = {
	page: PageId,
	element: ElementId,
	frame: Frame,
};

export type ElementId = string;

export type ElementKind = ({ Text: TextBlock }) & { Image?: never; Region?: never } | ({ Image: ImageElement }) & { Region?: never; Text?: never } | ({ Region: Region }) & { Image?: never; Text?: never };

export type ElementTextLayout = {
	element: ElementId,
	layout: TextLayout,
};

export type ElementTextStyle = {
	element: ElementId,
	style: TextStyle,
};

export type ExportFormat = "png" | "psd";

export type Flux2KleinConfig = {
	prompt?: string,
	padding_mask_crop?: number | null,
	strength?: number,
	num_inference_steps?: number,
	seed?: number,
};

export type FontDetectorConfig = {
	top_k?: number,
};

export type FontFaceStyleView = "normal" | "italic" | "oblique";

export type FontFaceView = {
	family_name: string,
	post_script_name: string,
	weight: number,
	stretch: number,
	style: FontFaceStyleView,
	source: FontSourceView,
	category: string | null,
	cached: boolean,
};

export type FontSlant = "Normal" | "Italic" | { Oblique: {
	angle_degrees: number,
} };

export type FontSourceView = "system" | "google";

export type Frame = {
	x: number,
	y: number,
	width: number,
	height: number,
	angle_degrees: number,
};

export type GeminiConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type GoogleCloudConfig = Record<string, never>;

export type GradientStop = {
	offset: number,
	color: [number, number, number, number],
};

export type Handle = "north_west" | "north" | "north_east" | "east" | "south_east" | "south" | "south_west" | "west" | "rotate";

export type HitTarget = { type: "element"; element: ElementId } | { type: "handle"; element: ElementId; handle: Handle };

export type ImageElement = {
	blob: BlobId,
	natural_size: Size,
	name: string,
};

export type InpaintingModel = {
	model: "lama",
} & LaMaConfig | {
	model: "aot-inpainting",
} & AotInpaintingConfig | {
	model: "flux2-klein",
} & Flux2KleinConfig | {
	model: "rorem-mixed",
} & RoremMixedConfig;

export type JobKind = "pipeline" | "import" | "export";

export type JobStatus = { state: "running"; id: RequestId; kind: JobKind; completed: number; total: number; phase: Phase | null; model: string | null } | { state: "finished"; id: RequestId } | { state: "failed"; id: RequestId; error: string } | { state: "cancelled"; id: RequestId };

export type KoharuLayoutRFDetrSeg2XLConfig = {
	text_threshold?: number | null,
	bubble_threshold?: number | null,
	panel_threshold?: number | null,
};

export type LaMaConfig = {
	hd_strategy?: LaMaHDStrategy,
	hd_strategy_crop_trigger_size?: number,
	hd_strategy_crop_margin?: number,
	hd_strategy_resize_limit?: number,
	keep_unmasked_area?: boolean,
};

export type LaMaHDStrategy = "original" | "resize" | "crop";

export type LmStudioConfig = {
	base_url: string,
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type LocalConfig = {
	model: string,
};

export type MangaOcrConfig = Record<string, never>;

export type MaskPlane = "text" | "brush";

export type ModelPrediction = {
	model: string,
	confidence: number,
};

export type OcrModel = { model: "paddleocr-vl-1.6" } | { model: "manga-ocr" } | { model: "baberu-ocr" };

export type OpenAiCompatibleConfig = {
	base_url: string,
	model: string,
	temperature: number | null,
	max_tokens: number | null,
};

export type OpenAiConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type OpenRouterConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type PaddleOcrVl1_6Config = Record<string, never>;

export type PageDelta = {
	id: PageId,
	name: string,
	size: Size,
	source: string,
	assets: AssetView,
	element_order: ElementId[],
	elements: Element[],
	deleted_elements: ElementId[],
};

export type PageId = string;

export type PageSummary = {
	id: PageId,
	name: string,
	size: Size,
	source: string,
	clean: string | null,
	elements: number,
};

export type PageView = {
	id: PageId,
	name: string,
	size: Size,
	source: string,
	assets: AssetView,
	elements: Element[],
};

export type Phase = "detection" | "ocr" | "translation" | "typography" | "inpainting";

export type PipelineConfig = {
	detection: DetectionModel,
	ocr: OcrModel,
	typography: TypographyModel,
	inpainting: InpaintingModel,
};

export type ProcessorId = "koharu-layout-rfdetr-seg-2xl" | "paddleocr-vl-1.6" | "manga-ocr" | "baberu-ocr" | "translation" | "font-detector" | "lama" | "aot-inpainting" | "flux2-klein" | "rorem-mixed";

export type ProjectDelta = {
	from: Revision,
	revision: Revision,
	name: string,
	page_order: PageId[],
	pages: PageSummary[],
	deleted_pages: PageId[],
	visible_page: PageDelta | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectHeader = {
	id: ProjectId,
	name: string,
	visible_page: PageId | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectId = string;

export type Providers = {
	provider: "local",
} & LocalConfig | {
	provider: "openai",
} & OpenAiConfig | {
	provider: "gemini",
} & GeminiConfig | {
	provider: "claude",
} & ClaudeConfig | {
	provider: "deepseek",
} & DeepSeekConfig | {
	provider: "openai_compatible",
} & OpenAiCompatibleConfig | {
	provider: "openrouter",
} & OpenRouterConfig | {
	provider: "lm_studio",
} & LmStudioConfig | {
	provider: "deepl",
} & DeepLConfig | { provider: "google_cloud_translation" } | { provider: "caiyun" };

export type Region = {
	kind: RegionKind,
	/**  Page-space polygon. An empty polygon means the element frame is authoritative. */
	polygon: ([number, number])[],
	/**  Non-zero label in the corresponding page mask, when an instance mask exists. */
	mask_id: number | null,
	reading_order: number | null,
	predictions: ModelPrediction[],
};

export type RegionKind = "Panel" | "Bubble";

export type RequestId = string;

export type Revision = number;

export type RoremMixedConfig = {
	prompt?: string,
	negative_prompt?: string,
	resolution?: number,
	mask_dilation?: number,
	num_inference_steps?: number,
	guidance_scale?: number,
	strength?: number,
	seed?: number,
};

export type RunTarget = { target: "all" } | { target: "phase"; phase: Phase } | { target: "processors"; processors: ProcessorId[] };

export type Scope = { scope: "project" } | { scope: "pages"; pages: PageId[] } | { scope: "region"; page: PageId; frame: Frame } | { scope: "elements"; elements: ElementId[] };

export type SettingsView = {
	pipeline: PipelineConfig,
	translation: TranslationSettings,
	local_translation_models: string[],
	target_languages: TargetLanguageView[],
	fonts: FontFaceView[],
};

export type Size = {
	width: number,
	height: number,
};

export type SourceText = {
	text: string,
	language: string | null,
	direction: TextDirection,
	confidence: number | null,
	lines: ([([number, number]), ([number, number]), ([number, number]), ([number, number])])[],
};

export type StrokePosition = "Inside" | "Center" | "Outside";

export type TargetLanguageView = {
	tag: string,
	name: string,
};

export type TextAlign = "Start" | "Center" | "End" | "Justify";

export type TextBlock = {
	source: SourceText | null,
	translation: string | null,
	style: TextStyle,
	layout: TextLayout,
	role: TextRole,
	panel: ElementId | null,
	bubble: ElementId | null,
	reading_order: number | null,
	/**  Page-space region polygon. Empty means the element frame is authoritative. */
	polygon: ([number, number])[],
	predictions: ModelPrediction[],
};

export type TextDecoration = {
	underline: boolean,
	strikethrough: boolean,
};

export type TextDirection = "Auto" | "Horizontal" | "Vertical";

export type TextEffect = {
	enabled: boolean,
	opacity: number,
	blend_mode: BlendMode,
	kind: TextEffectKind,
};

export type TextEffectKind = ({ Stroke: {
	color: [number, number, number, number],
	width: number,
	position: StrokePosition,
} }) & { Bevel?: never; ColorOverlay?: never; Glow?: never; GradientOverlay?: never; Satin?: never; Shadow?: never } | ({ Shadow: {
	inner: boolean,
	color: [number, number, number, number],
	angle_degrees: number,
	distance: number,
	spread: number,
	size: number,
} }) & { Bevel?: never; ColorOverlay?: never; Glow?: never; GradientOverlay?: never; Satin?: never; Stroke?: never } | ({ Glow: {
	inner: boolean,
	color: [number, number, number, number],
	spread: number,
	size: number,
} }) & { Bevel?: never; ColorOverlay?: never; GradientOverlay?: never; Satin?: never; Shadow?: never; Stroke?: never } | ({ Bevel: {
	style: BevelStyle,
	depth: number,
	size: number,
	soften: number,
	angle_degrees: number,
	altitude_degrees: number,
	highlight: [number, number, number, number],
	shadow: [number, number, number, number],
} }) & { ColorOverlay?: never; Glow?: never; GradientOverlay?: never; Satin?: never; Shadow?: never; Stroke?: never } | ({ Satin: {
	color: [number, number, number, number],
	angle_degrees: number,
	distance: number,
	size: number,
	invert: boolean,
} }) & { Bevel?: never; ColorOverlay?: never; Glow?: never; GradientOverlay?: never; Shadow?: never; Stroke?: never } | ({ ColorOverlay: {
	color: [number, number, number, number],
} }) & { Bevel?: never; Glow?: never; GradientOverlay?: never; Satin?: never; Shadow?: never; Stroke?: never } | ({ GradientOverlay: {
	stops: GradientStop[],
	angle_degrees: number,
	scale: number,
	reverse: boolean,
} }) & { Bevel?: never; ColorOverlay?: never; Glow?: never; Satin?: never; Shadow?: never; Stroke?: never };

export type TextFit = "Frame" | "Bubble";

export type TextLayout = {
	horizontal_align: TextAlign,
	vertical_align: VerticalAlign,
	writing_mode: WritingMode,
	/**  Insets ordered top, right, bottom, left. */
	inset: [number, number, number, number],
	overflow: TextOverflow,
	fit: TextFit,
};

export type TextOverflow = "Visible" | "Clip";

export type TextRole = "Dialogue" | "Narration" | "FreeText" | "Onomatopoeia" | "Furigana";

export type TextStyle = {
	font_families: string[],
	font_size: number,
	/**  OpenType weight in `1..=1000`. */
	font_weight: number,
	/**  Percentage where `100` is the normal face width. */
	font_stretch: number,
	font_slant: FontSlant,
	color: [number, number, number, number],
	/**  Ratio relative to `font_size`. */
	line_height: number,
	letter_spacing: number,
	word_spacing: number,
	horizontal_scale: number,
	vertical_scale: number,
	baseline_shift: number,
	/**  Rotation inside the text frame, separate from element rotation. */
	angle_degrees: number,
	decoration: TextDecoration,
	effects: TextEffect[],
};

export type TranslationCredentialsView = {
	openai: string,
	gemini: string,
	claude: string,
	deepseek: string,
	openai_compatible: string,
	openrouter: string,
	lm_studio: string,
	deepl: string,
	google_cloud_translation: string,
	caiyun: string,
};

export type TranslationSettings = {
	model: Providers,
	target_language: string,
	instructions: string | null,
	credentials: TranslationCredentialsView,
};

export type TypographyModel = {
	model: "font-detector",
} & FontDetectorConfig;

export type UiCommand = { type: "synchronize" } | { type: "create_project" } | { type: "open_project" } | { type: "close_project" } | { type: "import_pages" } | { type: "rename_page"; page: PageId; name: string } | { type: "delete_page"; page: PageId } | { type: "delete_pages"; pages: PageId[] } | { type: "move_page"; page: PageId; index: number } | { type: "add_text"; page: PageId; frame: Frame } | { type: "set_translation"; page: PageId; element: ElementId; translation: string | null } | { type: "set_text_style"; page: PageId; element: ElementId; style: TextStyle } | { type: "set_text_layout"; page: PageId; element: ElementId; layout: TextLayout } | { type: "set_text_styles"; page: PageId; elements: ElementTextStyle[] } | { type: "set_text_layouts"; page: PageId; elements: ElementTextLayout[] } | { type: "cache_font"; family: string; weight: number; italic: boolean } | { type: "set_element_frames"; elements: ElementFrame[] } | { type: "finish_transform" } | { type: "set_element_opacity"; page: PageId; elements: ElementId[]; opacity: number } | { type: "set_element_visibility"; page: PageId; elements: ElementId[]; visible: boolean } | { type: "delete_elements"; page: PageId; elements: ElementId[] } | { type: "move_element"; page: PageId; element: ElementId; index: number } | { type: "undo" } | { type: "redo" } | { type: "run_pipeline"; scope: Scope; target: RunTarget } | { type: "cancel_job"; job: RequestId } | { type: "export_pages"; pages: PageId[]; format: ExportFormat } | { type: "get_settings" } | { type: "set_settings"; pipeline: PipelineConfig; translation: TranslationSettings } | { type: "collect_garbage" };

export type UiError = {
	code: UiErrorCode,
	message: string,
	current_revision: Revision | null,
};

export type UiErrorCode = "stale_revision" | "no_project" | "not_found" | "busy" | "invalid_input" | "io_failed" | "internal";

export type UiEvent = ({ type: "accepted"; id: RequestId; revision: Revision }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; page?: never; pages?: never; project?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "command_cancelled"; id: RequestId; revision: Revision }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; page?: never; pages?: never; project?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "rejected"; id: RequestId; error: UiError }) & { auto_fit?: never; blobs?: never; bytes?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "problem"; error: UiError }) & { auto_fit?: never; blobs?: never; bytes?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "project_opened"; revision: Revision; project: ProjectHeader; pages: PageSummary[] }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "page_loaded"; revision: Revision; page: PageView }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; pages?: never; project?: never; settings?: never; target?: never; translation?: never; zoom?: never } | {
	type: "project_changed",
} & ProjectDelta | ({ type: "project_closed" }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; target?: never; translation?: never; zoom?: never } | ({ type: "hit_test"; id: number; target: HitTarget | null }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "view_changed"; zoom: number; translation: [number, number]; auto_fit: boolean }) & { blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; target?: never } | {
	type: "job_changed",
} & JobStatus | {
	type: "download_changed",
} & DownloadStatus | ({ type: "settings_changed"; settings: SettingsView }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; target?: never; translation?: never; zoom?: never } | ({ type: "garbage_collected"; blobs: number; bytes: number }) & { auto_fit?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; target?: never; translation?: never; zoom?: never };

export type VerticalAlign = "Top" | "Center" | "Bottom";

export type WindowAction = "drag" | "resize_east" | "resize_north" | "resize_north_east" | "resize_north_west" | "resize_south" | "resize_south_east" | "resize_south_west" | "resize_west" | "minimize" | "toggle_maximize" | "close";

export type WritingMode = "Auto" | "Horizontal" | "VerticalRightToLeft" | "VerticalLeftToRight";
