// This file is generated from the Rust desktop protocol by `cargo run -p koharu-app --bin generate`.
// Do not edit it by hand.

// This file has been generated by Specta. Do not edit this file manually.
export type AssetView = {
	source: string | null,
	clean: string | null,
	rendered: string | null,
	text_mask: string | null,
	coo_mask: string | null,
	bubble_mask: string | null,
	brush_mask: string | null,
};

export type Bounds = {
	x: number,
	y: number,
	width: number,
	height: number,
};

export type BridgeEvent = { type: "app"; payload: UiEvent };

export type BridgeMessage = { type: "ready"; dpr: number; width: number; height: number } | { type: "viewport"; x: number; y: number; width: number; height: number; dpr: number; background: [number, number, number] } | { type: "window"; action: WindowAction } | { type: "command"; id: RequestId; base: Revision; command: UiCommand } | { type: "interaction"; interaction: CanvasInteraction };

export type CaiyunConfig = Record<string, never>;

export type CanvasDisplay = {
	page: CanvasPageView,
	show_text: boolean,
	text_mask: CanvasMaskOverlay | null,
	brush_mask: CanvasMaskOverlay | null,
};

export type CanvasInteraction = { type: "show_page"; page: EntityId } | { type: "set_camera"; zoom: number; translation: [number, number] } | { type: "set_zoom"; zoom: number } | { type: "fit_window" } | { type: "set_display"; display: CanvasDisplay } | { type: "begin_transform"; elements: EntityId[] } | { type: "update_transform"; frame: number; elements: TransformFrame[] } | { type: "cancel_transform" } | { type: "begin_mask_stroke"; plane: MaskPlane; diameter: number; erase: boolean; x: number; y: number } | { type: "extend_mask_stroke"; x: number; y: number } | { type: "finish_mask_stroke" } | { type: "cancel_mask_stroke" };

export type CanvasMaskOverlay = {
	tint: [number, number, number, number],
	opacity: number,
};

export type CanvasPageView = "source" | "clean" | "rendered";

export type ClaudeConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type CredentialEdit = {
	configured: boolean,
	value: string | null,
	clear: boolean,
};

export type DeepLConfig = {
	base_url?: string | null,
};

export type DeepSeekConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type DetectionModel = {
	model: "koharu-layout-rfdetr-seg-2xl",
} & KoharuLayoutRFDetrSeg2XLConfig;

export type DeviceResourcesView = {
	name: string,
	selected: boolean,
	memory_budget_bytes: number | null,
	memory_used_bytes: number | null,
	utilization_percent: number | null,
};

export type DocumentId = string;

export type DownloadStatus = { state: "running"; id: number; name: string; completed: number; total: number } | { state: "finished"; id: number } | { state: "failed"; id: number; name: string; error: string };

export type EntityGeometry = {
	entity: EntityId,
	points: Point[],
};

export type EntityId = RecordId;

export type EntityTypography = {
	entity: EntityId,
	typography: TypographyIntent,
};

export type EntityView = {
	id: EntityId,
	parent: EntityId | null,
	geometry: GeometryView | null,
	visibility: VisibilityView,
	image: string | null,
	source_text: SourceTextView | null,
	translation: TranslationView | null,
	typography: TypographyIntent | null,
	region: RegionView | null,
};

export type ExportFormat = "png" | "psd";

export type Flux2KleinConfig = {
	prompt?: string,
};

export type FontFaceStyleView = "normal" | "italic" | "oblique";

export type FontFaceView = {
	family_name: string,
	post_script_name: string,
	weight: number,
	stretch: number,
	style: FontFaceStyleView,
	source: FontSourceView,
};

export type FontSourceView = "system" | "registered";

export type Frame = {
	x: number,
	y: number,
	width: number,
	height: number,
	angle_degrees: number,
};

export type GeminiConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type GeometryView = {
	points: Point[],
};

export type GoogleCloudConfig = Record<string, never>;

export type InpaintingModel = { model: "lama" } | { model: "aot-inpainting" } | {
	model: "flux2-klein",
} & Flux2KleinConfig | {
	model: "rorem-mixed",
} & RoremMixedConfig;

export type JobKind = "pipeline" | "import" | "export";

export type JobStatus = { state: "running"; id: RequestId; kind: JobKind; completed: number; total: number; page: EntityId | null; phase: Stage | null; model: string | null } | { state: "finished"; id: RequestId } | { state: "failed"; id: RequestId; error: string } | { state: "stopped"; id: RequestId };

export type KoharuLayoutRFDetrSeg2XLConfig = {
	text_threshold?: number | null,
	bubble_threshold?: number | null,
	panel_threshold?: number | null,
};

export type LmStudioConfig = {
	base_url: string,
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type LocalConfig = {
	model: string,
};

export type MaskPlane = "text" | "brush";

export type OcrModel = { model: "paddleocr-vl-1.6" } | { model: "manga-ocr" } | { model: "baberu-ocr" };

export type OpenAiCompatibleConfig = {
	base_url: string,
	model: string,
	temperature: number | null,
	max_tokens: number | null,
};

export type OpenAiConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type OpenRouterConfig = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
	thinking: boolean,
};

export type Operation = { operation: "full" } | { operation: "through"; stage: Stage } | { operation: "only"; stage: Stage };

export type PageSize = {
	width: number,
	height: number,
};

export type PageSummary = {
	id: EntityId,
	label: string,
	size: PageSize,
	source: string | null,
	clean: string | null,
	entities: number,
};

export type PageView = {
	id: EntityId,
	label: string,
	size: PageSize,
	assets: AssetView,
	entities: EntityView[],
};

export type PipelineConfig = {
	detection?: DetectionModel,
	ocr?: OcrModel,
	inpainting?: InpaintingModel,
};

export type Point = {
	x: number,
	y: number,
};

export type ProjectDelta = {
	from: Revision,
	revision: Revision,
	name: string,
	page_order: EntityId[],
	pages: PageSummary[],
	deleted_pages: EntityId[],
	visible_page: PageView | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectHeader = {
	id: ProjectId,
	name: string,
	visible_page: EntityId | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectId = DocumentId;

export type Providers = {
	provider: "local",
} & LocalConfig | {
	provider: "openai",
} & OpenAiConfig | {
	provider: "gemini",
} & GeminiConfig | {
	provider: "claude",
} & ClaudeConfig | {
	provider: "deepseek",
} & DeepSeekConfig | {
	provider: "openai_compatible",
} & OpenAiCompatibleConfig | {
	provider: "openrouter",
} & OpenRouterConfig | {
	provider: "lm_studio",
} & LmStudioConfig | {
	provider: "deepl",
} & DeepLConfig | { provider: "google_cloud_translation" } | { provider: "caiyun" };

export type RecordId = string;

export type RegionView = {
	kind: string,
	label: string | null,
};

export type RequestId = string;

export type Revision = number;

export type RoremMixedConfig = {
	prompt?: string,
	negative_prompt?: string,
};

export type Scope = { scope: "project" } | { scope: "pages"; value: EntityId[] } | { scope: "region"; value: {
	page: EntityId,
	bounds: Bounds,
} } | { scope: "entities"; value: EntityId[] };

export type SettingsView = {
	pipeline: PipelineConfig,
	translation: TranslationSettings,
	local_translation_models: string[],
	target_languages: TargetLanguageView[],
	fonts: FontFaceView[],
};

export type SourceTextView = {
	text: string,
	language: string | null,
};

export type Stage = "detection" | "ocr" | "translation" | "inpainting";

export type SystemResourcesView = {
	process_memory_bytes: number,
	system_memory_total_bytes: number,
	system_memory_used_bytes: number,
	process_cpu_percent: number,
	system_cpu_percent: number,
	devices: DeviceResourcesView[],
};

export type TargetLanguageView = {
	tag: string,
	name: string,
};

export type TextAlignment = "Start" | "Center" | "End" | "Justify";

export type TransformFrame = {
	element: EntityId,
	frame: Frame,
};

export type TranslationCredentialsView = {
	openai: CredentialEdit,
	gemini: CredentialEdit,
	claude: CredentialEdit,
	deepseek: CredentialEdit,
	openai_compatible: CredentialEdit,
	openrouter: CredentialEdit,
	lm_studio: CredentialEdit,
	deepl: CredentialEdit,
	google_cloud_translation: CredentialEdit,
	caiyun: CredentialEdit,
};

export type TranslationSettings = {
	model: Providers,
	target_language: string,
	instructions: string | null,
	credentials: TranslationCredentialsView,
};

export type TranslationView = {
	locale: string,
	text: string,
};

export type TypographyIntent = {
	preferred_font: string | null,
	size: number | null,
	alignment: TextAlignment | null,
	writing_mode: WritingMode | null,
};

export type UiCommand = { type: "synchronize" } | { type: "create_project" } | { type: "open_project" } | { type: "close_project" } | { type: "import_pages" } | { type: "rename_page"; page: EntityId; label: string } | { type: "delete_pages"; pages: EntityId[] } | { type: "move_page"; page: EntityId; index: number } | { type: "add_text"; page: EntityId; frame: Frame } | { type: "set_source_text"; entity: EntityId; text: string } | { type: "set_translation"; entity: EntityId; locale: string; text: string | null } | { type: "set_typography"; entities: EntityTypography[] } | { type: "set_geometry"; entities: EntityGeometry[] } | { type: "set_visibility"; entities: EntityId[]; visible: boolean | null; opacity: number | null } | { type: "delete_entities"; entities: EntityId[] } | { type: "move_entity"; entity: EntityId; parent: EntityId; index: number } | { type: "finish_transform" } | { type: "undo" } | { type: "redo" } | { type: "run_pipeline"; scope: Scope; operation: Operation } | { type: "stop_job"; job: RequestId } | { type: "export_pages"; pages: EntityId[]; format: ExportFormat } | { type: "get_settings" } | { type: "set_settings"; pipeline: PipelineConfig; translation: TranslationSettings } | { type: "collect_garbage" };

export type UiError = {
	code: UiErrorCode,
	message: string,
	current_revision: Revision | null,
};

export type UiErrorCode = "stale_revision" | "no_project" | "not_found" | "busy" | "invalid_input" | "io_failed" | "internal";

export type UiEvent = ({ type: "accepted"; id: RequestId; revision: Revision }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; page?: never; pages?: never; project?: never; resources?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "command_cancelled"; id: RequestId; revision: Revision }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; page?: never; pages?: never; project?: never; resources?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "rejected"; id: RequestId; error: UiError }) & { auto_fit?: never; blobs?: never; bytes?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "problem"; error: UiError }) & { auto_fit?: never; blobs?: never; bytes?: never; id?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "project_opened"; revision: Revision; project: ProjectHeader; pages: PageSummary[] }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; resources?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "page_loaded"; revision: Revision; page: PageView }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; pages?: never; project?: never; resources?: never; settings?: never; translation?: never; zoom?: never } | {
	type: "project_changed",
} & ProjectDelta | ({ type: "project_closed" }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "view_changed"; zoom: number; translation: [number, number]; auto_fit: boolean }) & { blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; settings?: never } | {
	type: "job_changed",
} & JobStatus | {
	type: "download_changed",
} & DownloadStatus | ({ type: "settings_changed"; settings: SettingsView }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; translation?: never; zoom?: never } | ({ type: "resources_changed"; resources: SystemResourcesView }) & { auto_fit?: never; blobs?: never; bytes?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; revision?: never; settings?: never; translation?: never; zoom?: never } | ({ type: "garbage_collected"; blobs: number; bytes: number }) & { auto_fit?: never; error?: never; id?: never; page?: never; pages?: never; project?: never; resources?: never; revision?: never; settings?: never; translation?: never; zoom?: never };

export type VisibilityView = {
	visible: boolean,
	opacity: number,
};

export type WindowAction = "drag" | "resize_east" | "resize_north" | "resize_north_east" | "resize_north_west" | "resize_south" | "resize_south_east" | "resize_south_west" | "resize_west" | "minimize" | "toggle_maximize" | "close";

export type WritingMode = "Horizontal" | "Vertical";
