/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  ApiKeyResponse,
  ApiKeyValue
} from '../schemas';

import { fetchApi } from '.././fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiKeyUrl = (provider: string,) => {




  return `/api/v1/providers/${provider}/api-key`
}

export const getApiKey = async (provider: string, options?: RequestInit): Promise<ApiKeyResponse> => {

  return fetchApi<ApiKeyResponse>(getGetApiKeyUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiKeyQueryKey = (provider: string,) => {
    return [
    `/api/v1/providers/${provider}/api-key`
    ] as const;
    }


export const getGetApiKeyQueryOptions = <TData = Awaited<ReturnType<typeof getApiKey>>, TError = ApiError>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiKeyQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiKey>>> = ({ signal }) => getApiKey(provider, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(provider),  gcTime: 300000, retry: 1,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiKey>>>
export type GetApiKeyQueryError = ApiError


export function useGetApiKey<TData = Awaited<ReturnType<typeof getApiKey>>, TError = ApiError>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKey>>,
          TError,
          Awaited<ReturnType<typeof getApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiKey<TData = Awaited<ReturnType<typeof getApiKey>>, TError = ApiError>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKey>>,
          TError,
          Awaited<ReturnType<typeof getApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiKey<TData = Awaited<ReturnType<typeof getApiKey>>, TError = ApiError>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiKey<TData = Awaited<ReturnType<typeof getApiKey>>, TError = ApiError>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKey>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiKeyQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getSetApiKeyUrl = (provider: string,) => {




  return `/api/v1/providers/${provider}/api-key`
}

export const setApiKey = async (provider: string,
    apiKeyValue: ApiKeyValue, options?: RequestInit): Promise<void> => {

  return fetchApi<void>(getSetApiKeyUrl(provider),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      apiKeyValue,)
  }
);}




export const getSetApiKeyMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setApiKey>>, TError,{provider: string;data: ApiKeyValue}, TContext>, request?: SecondParameter<typeof fetchApi>}
): UseMutationOptions<Awaited<ReturnType<typeof setApiKey>>, TError,{provider: string;data: ApiKeyValue}, TContext> => {

const mutationKey = ['setApiKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setApiKey>>, {provider: string;data: ApiKeyValue}> = (props) => {
          const {provider,data} = props ?? {};

          return  setApiKey(provider,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof setApiKey>>>
    export type SetApiKeyMutationBody = ApiKeyValue
    export type SetApiKeyMutationError = ApiError

    export const useSetApiKey = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setApiKey>>, TError,{provider: string;data: ApiKeyValue}, TContext>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setApiKey>>,
        TError,
        {provider: string;data: ApiKeyValue},
        TContext
      > => {
      return useMutation(getSetApiKeyMutationOptions(options), queryClient);
    }
