import { Logic } from "logic.slint";
import { ScrollView } from "std-widgets.slint";

export component ThumbnailItem inherits TouchArea {
    in property <string> title;
    in property <image> source;

    width: 100px;
    height: 140px;
    mouse-cursor: MouseCursor.pointer;

    VerticalLayout {
        spacing: 4px;

        rect := Rectangle {
            height: 116px;
            width: parent.width;
            background: white;
            border-radius: 4px;
            border-width: 1px;
            border-color: #E0E0E0;

            VerticalLayout {
                spacing: 2px;
                padding: 4px;

                Image {
                    source: root.source;
                    width: parent.width - 8px;
                    height: 108px;
                    image-fit: cover;
                }
            }
        }

        Text {
            text: root.title;
            color: #333333;
            font-size: 12px;
            font-weight: 400;
            horizontal-alignment: center;
            overflow: elide;
        }
    }

    states [
        hover when root.has-hover: {
            rect.background: #F5F5F5;
        }
    ]
}

export component ThumbnailPanel inherits Rectangle {
    width: 120px;
    background: #FAFAFA;
    border-width: 1px;
    border-color: #E0E0E0;

    Rectangle {
        width: parent.width;
        height: 1px;
        y: parent.height - 1px;
        background: #E0E0E0;
    }

    VerticalLayout {
        spacing: 4px;
        padding: 4px;

        Text {
            text: "Pages";
            color: #333333;
            font-size: 14px;
            font-weight: 400;
            horizontal-alignment: center;
        }

        ScrollView {
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    spacing: 2px;
                    @children
                }
            }
        }
    }
}
