# Start-Koharu-Dev-CUDA13.ps1
# Starts Koharu dev with CUDA Toolkit 13.0 explicitly selected.
# Generated by Install-Koharu-CUDA13.ps1.

param(
  [string]$RepoPath = "C:\Scripts\Program Projects\koharu",
  [string]$CudaRoot = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0"
)

$ErrorActionPreference = "Stop"

function OK($msg)   { Write-Host "[OK]   $msg" -ForegroundColor Green }
function INFO($msg) { Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function BAD($msg)  { Write-Host "[FAIL] $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "Starting Koharu dev with CUDA 13.0" -ForegroundColor White
Write-Host "Repo: $RepoPath"
Write-Host "CUDA: $CudaRoot"
Write-Host ""

if (!(Test-Path $RepoPath)) {
  BAD "Repo not found: $RepoPath"
  exit 1
}

if (!(Test-Path $CudaRoot)) {
  BAD "CUDA Toolkit 13.0 not found at: $CudaRoot"
  exit 1
}

$nvcc = Join-Path $CudaRoot "bin\nvcc.exe"
if (!(Test-Path $nvcc)) {
  BAD "nvcc.exe not found at: $nvcc"
  exit 1
}

$llvm = "C:\Program Files\LLVM\bin"
if (!(Test-Path $llvm)) {
  BAD "LLVM bin not found at: $llvm"
  exit 1
}

$env:CUDA_PATH = $CudaRoot
$env:CUDA_HOME = $CudaRoot
$env:CUDA_ROOT = $CudaRoot
$env:CUDA_COMPUTE_CAP = "89"
$env:LIBCLANG_PATH = $llvm
$env:NVCC_PREPEND_FLAGS = "--std=c++17 -Xcompiler /std:c++17 -Xcompiler /Zc:preprocessor -Xcompiler /Zc:__cplusplus -DCCCL_IGNORE_DEPRECATED_CPP_DIALECT"

$cudaBin = Join-Path $CudaRoot "bin"
$env:Path = "$cudaBin;$llvm;$env:Path"

Push-Location $RepoPath
try {
  INFO "nvcc actually being used:"
  where.exe nvcc
  & $nvcc --version

  INFO "nvidia-smi:"
  nvidia-smi

  Write-Host ""
  OK "Environment prepared. Starting bun dev..."
  bun dev
}
finally {
  Pop-Location
}
