/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { AppDataConfigUpdate } from './appDataConfigUpdate'
import type { AppLlmConfigUpdate } from './appLlmConfigUpdate'

export interface AppConfigUpdate {
  data: AppDataConfigUpdate
  llm?: AppLlmConfigUpdate
}
