/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { AppDataConfig } from './appDataConfig'
import type { AppLlmConfig } from './appLlmConfig'

export interface AppConfig {
  data: AppDataConfig
  llm?: AppLlmConfig
}
