/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface AppLlmProviderConfig {
  /** @nullable */
  baseUrl?: string | null
  hasApiKey: boolean
  id: string
}
