/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface AppLlmProviderConfigUpdate {
  /** @nullable */
  apiKey?: string | null
  /** @nullable */
  baseUrl?: string | null
  clearApiKey?: boolean
  id: string
}
