/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { AppLlmProviderConfigUpdate } from './appLlmProviderConfigUpdate'

export interface AppLlmConfigUpdate {
  providers?: AppLlmProviderConfigUpdate[]
}
