/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { TextBlockDetail } from './textBlockDetail'

export interface DocumentDetail {
  /** @nullable */
  brushLayer?: number[] | null
  /** @minimum 0 */
  height: number
  id: string
  image: number[]
  /** @nullable */
  inpainted?: number[] | null
  name: string
  path: string
  /** @nullable */
  rendered?: number[] | null
  /** @nullable */
  segment?: number[] | null
  textBlocks: TextBlockDetail[]
  /** @minimum 0 */
  width: number
}
