/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ExportLayer = (typeof ExportLayer)[keyof typeof ExportLayer]

export const ExportLayer = {
  rendered: 'rendered',
  inpainted: 'inpainted',
} as const
