/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ExportLayer } from './exportLayer'

export type ExportDocumentParams = {
  layer?: null | ExportLayer
}
