/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ExportLayer } from './exportLayer';

export interface ExportBatchRequest {
  /** @nullable */
  documentIds?: string[] | null;
  layer?: null | ExportLayer;
}
