/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { EngineCatalogEntry } from './engineCatalogEntry'

export type GetEngineCatalog200 = {
  detectors: EngineCatalogEntry[]
  inpainters: EngineCatalogEntry[]
  ocr: EngineCatalogEntry[]
  renderers: EngineCatalogEntry[]
  segmenters: EngineCatalogEntry[]
  translators: EngineCatalogEntry[]
}
