/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ImportTranslationsSkip } from './importTranslationsSkip'

export interface ImportTranslationsResponse {
  /**
   * Number of pages whose translations were applied.
   * @minimum 0
   */
  applied: number
  /** Top-level parse errors (e.g. could not extract JSON). Empty on success. */
  errors: string[]
  /** Per-page reasons for pages that were skipped (missing from response,
  length mismatch, etc.). Not an error — partial success is normal. */
  skipped: ImportTranslationsSkip[]
}
