/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DocumentSummary } from './documentSummary'

export interface ImportResult {
  documents: DocumentSummary[]
  /** @minimum 0 */
  totalCount: number
}
