/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ImportMode } from './importMode'

export type ImportDocumentsParams = {
  mode?: null | ImportMode
}
