/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ImportMode = (typeof ImportMode)[keyof typeof ImportMode]

export const ImportMode = {
  replace: 'replace',
  append: 'append',
} as const
