/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ImportTranslationsRequest {
  /** User-supplied JSON text. May be a raw object, wrapped in a
  markdown ```json fence, or surrounded by prose. The server
  extracts the first JSON object it can find. */
  payload: string
}
