/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { JobStatus } from './jobStatus'

export interface JobFinishedEvent {
  /** @nullable */
  error?: string | null
  id: string
  status: JobStatus
}
