/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { JobStatus } from './jobStatus';

export interface JobState {
  /** @minimum 0 */
  currentDocument: number;
  /** @minimum 0 */
  currentStepIndex: number;
  /** @nullable */
  error?: string | null;
  id: string;
  kind: string;
  /** @minimum 0 */
  overallPercent: number;
  status: JobStatus;
  /** @nullable */
  step?: string | null;
  /** @minimum 0 */
  totalDocuments: number;
  /** @minimum 0 */
  totalSteps: number;
}
