/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]

export const JobStatus = {
  running: 'running',
  completed: 'completed',
  cancelled: 'cancelled',
  failed: 'failed',
} as const
