/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ListLlmModelsParams = {
/**
 * @nullable
 */
language?: string | null;
/**
 * @nullable
 */
openaiCompatibleBaseUrl?: string | null;
};
