/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmTarget } from './llmTarget';

export interface LlmCatalogModel {
  downloaded: boolean;
  downloadSize?: string;
  languages: string[];
  name: string;
  target: LlmTarget;
}
