/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface LlmLoadRequest {
  /** @nullable */
  apiKey?: string | null;
  /** @nullable */
  baseUrl?: string | null;
  /** @nullable */
  customSystemPrompt?: string | null;
  id: string;
  /**
     * @minimum 0
     * @nullable
     */
  maxTokens?: number | null;
  /** @nullable */
  temperature?: number | null;
}
