/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmGenerationOptions } from './llmGenerationOptions';
import type { LlmTarget } from './llmTarget';

export interface LlmLoadRequest {
  options?: null | LlmGenerationOptions;
  target: LlmTarget;
}
