/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface LlmPingResponse {
  /** @nullable */
  error?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  latencyMs?: number | null;
  models: string[];
  ok: boolean;
}
