/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmStateStatus } from './llmStateStatus';

export interface LlmState {
  /** @nullable */
  error?: string | null;
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  source?: string | null;
  status: LlmStateStatus;
}
