/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type LlmTargetKind = (typeof LlmTargetKind)[keyof typeof LlmTargetKind]

export const LlmTargetKind = {
  local: 'local',
  provider: 'provider',
} as const
