/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { Region } from './region'

export interface MaskRegionRequest {
  data: number[]
  region?: null | Region
}
