/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface MetaInfo {
  /**
   * Workers a CPU-bound pipeline stage gets under auto sizing. Depends on
   * the host's core count, so only the server can report it.
   * @minimum 0
   */
  cpuWorkers: number
  mlDevice: string
  version: string
}
