/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

/**
 * Engine selection for each pipeline stage.
 * Values are engine IDs (e.g. "pp-doclayout-v3", "comic-text-detector").
 * Empty string means use default.
 */
export interface PipelineConfig {
  bubble_segmenter?: string
  detector?: string
  font_detector?: string
  inpainter?: string
  /**
   * Upper bound on pages any single stage folds into one model call.
   * `0` = auto, `1` = disable batching but keep stage overlap.
   *
   * Batch size is the larger VRAM lever of the two, so try lowering this
   * before `max_inflight_pages`.
   * @minimum 0
   */
  max_batch_pages?: number
  /**
   * Maximum pages moving through the pipeline at once. `0` = auto (one per
   * stage, so every stage can stay busy).
   *
   * Set to `1` to restore fully sequential processing: one page finishes
   * every step before the next starts, and no stage ever batches. That is
   * the escape hatch if parallelism causes trouble.
   * @minimum 0
   */
  max_inflight_pages?: number
  ocr?: string
  renderer?: string
  segmenter?: string
  translator?: string
}
