/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface PipelineConfigPatch {
  /** @nullable */
  bubbleSegmenter?: string | null
  /** @nullable */
  detector?: string | null
  /** @nullable */
  fontDetector?: string | null
  /** @nullable */
  inpainter?: string | null
  /**
   * Cap on pages a stage folds into one model call. `0` = auto, `1` =
   * no batching.
   * @minimum 0
   * @nullable
   */
  maxBatchPages?: number | null
  /**
   * Pages allowed in the pipeline at once. `0` = auto (one per step), `1` =
   * fully sequential.
   * @minimum 0
   * @nullable
   */
  maxInflightPages?: number | null
  /** @nullable */
  ocr?: string | null
  /** @nullable */
  renderer?: string | null
  /** @nullable */
  segmenter?: string | null
  /** @nullable */
  translator?: string | null
}
