/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { PipelineLlmRequest } from './pipelineLlmRequest'
import type { TextShaderEffect } from './textShaderEffect'
import type { TextStrokeStyle } from './textStrokeStyle'

export interface PipelineJobRequest {
  /** @nullable */
  documentId?: string | null
  /** @nullable */
  language?: string | null
  llm?: null | PipelineLlmRequest
  shaderEffect?: null | TextShaderEffect
  shaderStroke?: null | TextStrokeStyle
}
