/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ProviderConfig {
  /**
     * Populated from the keyring on `load()`, never written to config.toml.
  Serializes as `"[REDACTED]"` in API responses.
  Populated from keyring on `load()`. Serializes as `"[REDACTED]"`.
     * @nullable
     */
  api_key?: string | null
  /** @nullable */
  base_url?: string | null
  id: string
}
