/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { NodeId } from './nodeId'
import type { PageId } from './pageId'
import type { ReadingOrder } from './readingOrder'
import type { Region } from './region'

export interface StartPipelineRequest {
  /** @nullable */
  defaultFont?: string | null
  /**
   * `None` → whole project, `Some(pages)` → just those pages.
   * @nullable
   */
  pages?: PageId[] | null
  readingOrder?: null | ReadingOrder
  region?: null | Region
  /** Engine ids (`inventory::submit!` ids) to run in order. */
  steps: string[]
  /** @nullable */
  systemPrompt?: string | null
  /** @nullable */
  targetLanguage?: string | null
  /**
   * Optional text-node ids for engines that can operate on individual blocks.
   * @nullable
   */
  textNodeIds?: NodeId[] | null
  /** When true, translate with chapter-level context across all pages in scope. */
  chapterContextTranslation?: boolean
  /** Token budget per chapter translation chunk (256–8192, default 4096). */
  chapterTranslationTokenBudget?: number
  /** Maximum blocks per chapter translation chunk (1–200, default 100). */
  chapterTranslationMaxBlocks?: number
}
