/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeId } from './nodeId';
import type { PageId } from './pageId';
import type { ReadingOrder } from './readingOrder';
import type { Region } from './region';

export interface StartPipelineRequest {
  /** @nullable */
  defaultFont?: string | null;
  /**
     * If enabled, merge any ops generated by this with the entry above it, ensuring that they undo as a batch.
     * Used for implementing auto-render so that the render doesn't get a separate undo entry.
     */
  mergeWithPreviousOp?: boolean;
  /**
     * `None` → whole project, `Some(pages)` → just those pages.
     * @nullable
     */
  pages?: PageId[] | null;
  readingOrder?: null | ReadingOrder;
  region?: null | Region;
  /** Engine ids (`inventory::submit!` ids) to run in order. */
  steps: string[];
  /** @nullable */
  systemPrompt?: string | null;
  /** @nullable */
  targetLanguage?: string | null;
  /**
     * Optional text-node ids for engines that can operate on individual blocks.
     * @nullable
     */
  textNodeIds?: NodeId[] | null;
}
