/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { PageId } from './pageId'
import type { Region } from './region'

export interface StartPipelineRequest {
  /** @nullable */
  defaultFont?: string | null
  /**
   * `None` → whole project, `Some(pages)` → just those pages.
   * @nullable
   */
  pages?: PageId[] | null
  region?: null | Region
  /** Engine ids (`inventory::submit!` ids) to run in order. */
  steps: string[]
  /** @nullable */
  systemPrompt?: string | null
  /** @nullable */
  targetLanguage?: string | null
}
