/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { TextStyle } from './textStyle';

export interface TextBlockInput {
  height: number;
  /** @nullable */
  id?: string | null;
  style?: null | TextStyle;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  translation?: string | null;
  width: number;
  x: number;
  y: number;
}
