/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { TextStyle } from './textStyle';

export interface TextBlockPatch {
  /** @nullable */
  height?: number | null;
  style?: null | TextStyle;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  translation?: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  x?: number | null;
  /** @nullable */
  y?: number | null;
}
