/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type TextDirection = (typeof TextDirection)[keyof typeof TextDirection]

export const TextDirection = {
  Horizontal: 'Horizontal',
  Vertical: 'Vertical',
} as const
