/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { FontPrediction } from './fontPrediction'
import type { TextDirection } from './textDirection'
import type { TextStyle } from './textStyle'

export interface TextBlockDetail {
  confidence: number
  /** @nullable */
  detectedFontSizePx?: number | null
  /** @nullable */
  detector?: string | null
  fontPrediction?: null | FontPrediction
  height: number
  id: string
  /** @nullable */
  linePolygons?: number[][][] | null
  /** @nullable */
  renderHeight?: number | null
  /** @nullable */
  renderWidth?: number | null
  /**
   * Actual render area position/size (when bubble expansion is used).
   * @nullable
   */
  renderX?: number | null
  /** @nullable */
  renderY?: number | null
  /**
   * Blob hash for the rendered text block sprite.
   * @nullable
   */
  rendered?: string | null
  renderedDirection?: null | TextDirection
  /** @nullable */
  rotationDeg?: number | null
  sourceDirection?: null | TextDirection
  /** @nullable */
  sourceLanguage?: string | null
  style?: null | TextStyle
  /** @nullable */
  text?: string | null
  /** @nullable */
  translation?: string | null
  width: number
  x: number
  y: number
}
