/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

import type { DeeplTranslateOptions } from './deeplTranslateOptions'

export interface TranslateRequest {
  /** @nullable */
  language?: string | null
  /** @nullable */
  systemPrompt?: string | null
  /** @nullable */
  textBlockId?: string | null
  /** @nullable */
  deepl?: DeeplTranslateOptions | null
}
