/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DataConfig } from './dataConfig'
import type { ProviderConfig } from './providerConfig'

export type UpdateConfigBody = {
  data?: DataConfig
  providers?: ProviderConfig[]
}
