/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type VerticalAlign = (typeof VerticalAlign)[keyof typeof VerticalAlign]

export const VerticalAlign = {
  top: 'top',
  center: 'center',
  bottom: 'bottom',
} as const
