import {
    AppMenuBar,
    AppMenu,
    AppMenuItem,
    AppMenuSeparator,
} from "menubar.slint";
import { Logic } from "logic.slint";
import { ThumbnailPanel, ThumbnailItem } from "thumbnail.slint";

// re-export for the native code
// refer: https://github.com/slint-ui/slint/blob/24d37751e8245af46722e8e8aa9fb74bf6639489/examples/printerdemo/ui/printerdemo.slint#L11
export { Logic }

export component App inherits Window {
    max-width: 3840px;
    max-height: 2160px;
    preferred-width: 1024px;
    preferred-height: 768px;
    title: "Koharu";
    icon: @image-url("assets/Koharu_Halo.webp");

    VerticalLayout {
        AppMenuBar {
            AppMenu {
                title: "File";

                AppMenuItem {
                    title: "Open File...";
                }
            }

            AppMenu {
                title: "Help";

                AppMenuItem {
                    title: "Discord";
                    clicked => {
                        Logic.open_external("https://discord.gg/mHvHkxGnUY");
                    }
                }

                AppMenuItem {
                    title: "GitHub";
                    clicked => {
                        Logic.open_external("https://github.com/mayocream/koharu");
                    }
                }
            }
        }

        HorizontalLayout {
            ThumbnailPanel {
                // Test thumbnails
                for i in ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"]: ThumbnailItem {
                    title: i;
                    source: @image-url("assets/images/Koharu_Portrait.webp");
                }
            }
        }
    }
}
