/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  ListLlmModelsParams,
  LlmLoadRequest,
  LlmModelInfo,
  LlmPingRequest,
  LlmPingResponse,
  LlmState
} from '../schemas';

import { fetchApi } from '.././fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetLlmUrl = () => {




  return `/api/v1/llm`
}

export const getLlm = async ( options?: RequestInit): Promise<LlmState> => {

  return fetchApi<LlmState>(getGetLlmUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLlmQueryKey = () => {
    return [
    `/api/v1/llm`
    ] as const;
    }


export const getGetLlmQueryOptions = <TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLlmQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLlm>>> = ({ signal }) => getLlm({ signal, ...requestOptions });





   return  { queryKey, queryFn,   gcTime: 300000, retry: 1,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLlmQueryResult = NonNullable<Awaited<ReturnType<typeof getLlm>>>
export type GetLlmQueryError = ApiError


export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlm>>,
          TError,
          Awaited<ReturnType<typeof getLlm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLlm>>,
          TError,
          Awaited<ReturnType<typeof getLlm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLlm<TData = Awaited<ReturnType<typeof getLlm>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLlm>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLlmQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getLoadLlmUrl = () => {




  return `/api/v1/llm`
}

export const loadLlm = async (llmLoadRequest: LlmLoadRequest, options?: RequestInit): Promise<LlmState> => {

  return fetchApi<LlmState>(getLoadLlmUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      llmLoadRequest,)
  }
);}




export const getLoadLlmMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadLlm>>, TError,{data: LlmLoadRequest}, TContext>, request?: SecondParameter<typeof fetchApi>}
): UseMutationOptions<Awaited<ReturnType<typeof loadLlm>>, TError,{data: LlmLoadRequest}, TContext> => {

const mutationKey = ['loadLlm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loadLlm>>, {data: LlmLoadRequest}> = (props) => {
          const {data} = props ?? {};

          return  loadLlm(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoadLlmMutationResult = NonNullable<Awaited<ReturnType<typeof loadLlm>>>
    export type LoadLlmMutationBody = LlmLoadRequest
    export type LoadLlmMutationError = ApiError

    export const useLoadLlm = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadLlm>>, TError,{data: LlmLoadRequest}, TContext>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loadLlm>>,
        TError,
        {data: LlmLoadRequest},
        TContext
      > => {
      return useMutation(getLoadLlmMutationOptions(options), queryClient);
    }
    export const getUnloadLlmUrl = () => {




  return `/api/v1/llm`
}

export const unloadLlm = async ( options?: RequestInit): Promise<LlmState> => {

  return fetchApi<LlmState>(getUnloadLlmUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getUnloadLlmMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError,void, TContext>, request?: SecondParameter<typeof fetchApi>}
): UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError,void, TContext> => {

const mutationKey = ['unloadLlm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unloadLlm>>, void> = () => {


          return  unloadLlm(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnloadLlmMutationResult = NonNullable<Awaited<ReturnType<typeof unloadLlm>>>

    export type UnloadLlmMutationError = ApiError

    export const useUnloadLlm = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unloadLlm>>, TError,void, TContext>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unloadLlm>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUnloadLlmMutationOptions(options), queryClient);
    }
    export const getCheckLlmHealthUrl = () => {




  return `/api/v1/llm/health`
}

export const checkLlmHealth = async (llmPingRequest: LlmPingRequest, options?: RequestInit): Promise<LlmPingResponse> => {

  return fetchApi<LlmPingResponse>(getCheckLlmHealthUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      llmPingRequest,)
  }
);}




export const getCheckLlmHealthMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkLlmHealth>>, TError,{data: LlmPingRequest}, TContext>, request?: SecondParameter<typeof fetchApi>}
): UseMutationOptions<Awaited<ReturnType<typeof checkLlmHealth>>, TError,{data: LlmPingRequest}, TContext> => {

const mutationKey = ['checkLlmHealth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkLlmHealth>>, {data: LlmPingRequest}> = (props) => {
          const {data} = props ?? {};

          return  checkLlmHealth(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CheckLlmHealthMutationResult = NonNullable<Awaited<ReturnType<typeof checkLlmHealth>>>
    export type CheckLlmHealthMutationBody = LlmPingRequest
    export type CheckLlmHealthMutationError = unknown

    export const useCheckLlmHealth = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkLlmHealth>>, TError,{data: LlmPingRequest}, TContext>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkLlmHealth>>,
        TError,
        {data: LlmPingRequest},
        TContext
      > => {
      return useMutation(getCheckLlmHealthMutationOptions(options), queryClient);
    }
    export const getListLlmModelsUrl = (params?: ListLlmModelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/llm/models?${stringifiedParams}` : `/api/v1/llm/models`
}

export const listLlmModels = async (params?: ListLlmModelsParams, options?: RequestInit): Promise<LlmModelInfo[]> => {

  return fetchApi<LlmModelInfo[]>(getListLlmModelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLlmModelsQueryKey = (params?: ListLlmModelsParams,) => {
    return [
    `/api/v1/llm/models`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLlmModelsQueryOptions = <TData = Awaited<ReturnType<typeof listLlmModels>>, TError = ApiError>(params?: ListLlmModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLlmModelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLlmModels>>> = ({ signal }) => listLlmModels(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   gcTime: 300000, retry: 1,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLlmModelsQueryResult = NonNullable<Awaited<ReturnType<typeof listLlmModels>>>
export type ListLlmModelsQueryError = ApiError


export function useListLlmModels<TData = Awaited<ReturnType<typeof listLlmModels>>, TError = ApiError>(
 params: undefined |  ListLlmModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLlmModels>>,
          TError,
          Awaited<ReturnType<typeof listLlmModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLlmModels<TData = Awaited<ReturnType<typeof listLlmModels>>, TError = ApiError>(
 params?: ListLlmModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLlmModels>>,
          TError,
          Awaited<ReturnType<typeof listLlmModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLlmModels<TData = Awaited<ReturnType<typeof listLlmModels>>, TError = ApiError>(
 params?: ListLlmModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListLlmModels<TData = Awaited<ReturnType<typeof listLlmModels>>, TError = ApiError>(
 params?: ListLlmModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLlmModels>>, TError, TData>>, request?: SecondParameter<typeof fetchApi>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLlmModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




