name: Test

on:
  push:
    branches: ['main']
  pull_request:

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-14/lib
jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      # refer: https://v2.tauri.app/start/prerequisites/#linux
      - run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            fonts-noto-cjk \
            llvm-dev \
            libclang-dev \
            clang
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
      - run: cargo test --no-run
      - run: cargo test --workspace --tests
